// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: application_metadata_message.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ApplicationMetadataMessage_Type int32

const (
	ApplicationMetadataMessage_UNKNOWN                                 ApplicationMetadataMessage_Type = 0
	ApplicationMetadataMessage_CHAT_MESSAGE                            ApplicationMetadataMessage_Type = 1
	ApplicationMetadataMessage_CONTACT_UPDATE                          ApplicationMetadataMessage_Type = 2
	ApplicationMetadataMessage_MEMBERSHIP_UPDATE_MESSAGE               ApplicationMetadataMessage_Type = 3
	ApplicationMetadataMessage_PAIR_INSTALLATION                       ApplicationMetadataMessage_Type = 4
	ApplicationMetadataMessage_SYNC_INSTALLATION                       ApplicationMetadataMessage_Type = 5
	ApplicationMetadataMessage_REQUEST_ADDRESS_FOR_TRANSACTION         ApplicationMetadataMessage_Type = 6
	ApplicationMetadataMessage_ACCEPT_REQUEST_ADDRESS_FOR_TRANSACTION  ApplicationMetadataMessage_Type = 7
	ApplicationMetadataMessage_DECLINE_REQUEST_ADDRESS_FOR_TRANSACTION ApplicationMetadataMessage_Type = 8
	ApplicationMetadataMessage_REQUEST_TRANSACTION                     ApplicationMetadataMessage_Type = 9
	ApplicationMetadataMessage_SEND_TRANSACTION                        ApplicationMetadataMessage_Type = 10
	ApplicationMetadataMessage_DECLINE_REQUEST_TRANSACTION             ApplicationMetadataMessage_Type = 11
	ApplicationMetadataMessage_SYNC_INSTALLATION_CONTACT               ApplicationMetadataMessage_Type = 12
	ApplicationMetadataMessage_SYNC_INSTALLATION_ACCOUNT               ApplicationMetadataMessage_Type = 13
	ApplicationMetadataMessage_SYNC_INSTALLATION_PUBLIC_CHAT           ApplicationMetadataMessage_Type = 14
	ApplicationMetadataMessage_CONTACT_CODE_ADVERTISEMENT              ApplicationMetadataMessage_Type = 15
	ApplicationMetadataMessage_PUSH_NOTIFICATION_REGISTRATION          ApplicationMetadataMessage_Type = 16
	ApplicationMetadataMessage_PUSH_NOTIFICATION_REGISTRATION_RESPONSE ApplicationMetadataMessage_Type = 17
	ApplicationMetadataMessage_PUSH_NOTIFICATION_QUERY                 ApplicationMetadataMessage_Type = 18
	ApplicationMetadataMessage_PUSH_NOTIFICATION_QUERY_RESPONSE        ApplicationMetadataMessage_Type = 19
	ApplicationMetadataMessage_PUSH_NOTIFICATION_REQUEST               ApplicationMetadataMessage_Type = 20
	ApplicationMetadataMessage_PUSH_NOTIFICATION_RESPONSE              ApplicationMetadataMessage_Type = 21
	ApplicationMetadataMessage_EMOJI_REACTION                          ApplicationMetadataMessage_Type = 22
	ApplicationMetadataMessage_GROUP_CHAT_INVITATION                   ApplicationMetadataMessage_Type = 23
	ApplicationMetadataMessage_CHAT_IDENTITY                           ApplicationMetadataMessage_Type = 24
	ApplicationMetadataMessage_COMMUNITY_DESCRIPTION                   ApplicationMetadataMessage_Type = 25
	ApplicationMetadataMessage_COMMUNITY_INVITATION                    ApplicationMetadataMessage_Type = 26
	ApplicationMetadataMessage_COMMUNITY_REQUEST_TO_JOIN               ApplicationMetadataMessage_Type = 27
	ApplicationMetadataMessage_PIN_MESSAGE                             ApplicationMetadataMessage_Type = 28
	ApplicationMetadataMessage_EDIT_MESSAGE                            ApplicationMetadataMessage_Type = 29
	ApplicationMetadataMessage_STATUS_UPDATE                           ApplicationMetadataMessage_Type = 30
	ApplicationMetadataMessage_DELETE_MESSAGE                          ApplicationMetadataMessage_Type = 31
	ApplicationMetadataMessage_SYNC_INSTALLATION_COMMUNITY             ApplicationMetadataMessage_Type = 32
	ApplicationMetadataMessage_ANONYMOUS_METRIC_BATCH                  ApplicationMetadataMessage_Type = 33
	ApplicationMetadataMessage_SYNC_CHAT_REMOVED                       ApplicationMetadataMessage_Type = 34
	ApplicationMetadataMessage_SYNC_CHAT_MESSAGES_READ                 ApplicationMetadataMessage_Type = 35
	ApplicationMetadataMessage_BACKUP                                  ApplicationMetadataMessage_Type = 36
	ApplicationMetadataMessage_SYNC_ACTIVITY_CENTER_READ               ApplicationMetadataMessage_Type = 37
	ApplicationMetadataMessage_SYNC_ACTIVITY_CENTER_ACCEPTED           ApplicationMetadataMessage_Type = 38
	ApplicationMetadataMessage_SYNC_ACTIVITY_CENTER_DISMISSED          ApplicationMetadataMessage_Type = 39
	ApplicationMetadataMessage_SYNC_BOOKMARK                           ApplicationMetadataMessage_Type = 40
	ApplicationMetadataMessage_SYNC_CLEAR_HISTORY                      ApplicationMetadataMessage_Type = 41
	ApplicationMetadataMessage_SYNC_SETTING                            ApplicationMetadataMessage_Type = 42
)

var ApplicationMetadataMessage_Type_name = map[int32]string{
	0:  "UNKNOWN",
	1:  "CHAT_MESSAGE",
	2:  "CONTACT_UPDATE",
	3:  "MEMBERSHIP_UPDATE_MESSAGE",
	4:  "PAIR_INSTALLATION",
	5:  "SYNC_INSTALLATION",
	6:  "REQUEST_ADDRESS_FOR_TRANSACTION",
	7:  "ACCEPT_REQUEST_ADDRESS_FOR_TRANSACTION",
	8:  "DECLINE_REQUEST_ADDRESS_FOR_TRANSACTION",
	9:  "REQUEST_TRANSACTION",
	10: "SEND_TRANSACTION",
	11: "DECLINE_REQUEST_TRANSACTION",
	12: "SYNC_INSTALLATION_CONTACT",
	13: "SYNC_INSTALLATION_ACCOUNT",
	14: "SYNC_INSTALLATION_PUBLIC_CHAT",
	15: "CONTACT_CODE_ADVERTISEMENT",
	16: "PUSH_NOTIFICATION_REGISTRATION",
	17: "PUSH_NOTIFICATION_REGISTRATION_RESPONSE",
	18: "PUSH_NOTIFICATION_QUERY",
	19: "PUSH_NOTIFICATION_QUERY_RESPONSE",
	20: "PUSH_NOTIFICATION_REQUEST",
	21: "PUSH_NOTIFICATION_RESPONSE",
	22: "EMOJI_REACTION",
	23: "GROUP_CHAT_INVITATION",
	24: "CHAT_IDENTITY",
	25: "COMMUNITY_DESCRIPTION",
	26: "COMMUNITY_INVITATION",
	27: "COMMUNITY_REQUEST_TO_JOIN",
	28: "PIN_MESSAGE",
	29: "EDIT_MESSAGE",
	30: "STATUS_UPDATE",
	31: "DELETE_MESSAGE",
	32: "SYNC_INSTALLATION_COMMUNITY",
	33: "ANONYMOUS_METRIC_BATCH",
	34: "SYNC_CHAT_REMOVED",
	35: "SYNC_CHAT_MESSAGES_READ",
	36: "BACKUP",
	37: "SYNC_ACTIVITY_CENTER_READ",
	38: "SYNC_ACTIVITY_CENTER_ACCEPTED",
	39: "SYNC_ACTIVITY_CENTER_DISMISSED",
	40: "SYNC_BOOKMARK",
	41: "SYNC_CLEAR_HISTORY",
	42: "SYNC_SETTING",
}

var ApplicationMetadataMessage_Type_value = map[string]int32{
	"UNKNOWN":                                 0,
	"CHAT_MESSAGE":                            1,
	"CONTACT_UPDATE":                          2,
	"MEMBERSHIP_UPDATE_MESSAGE":               3,
	"PAIR_INSTALLATION":                       4,
	"SYNC_INSTALLATION":                       5,
	"REQUEST_ADDRESS_FOR_TRANSACTION":         6,
	"ACCEPT_REQUEST_ADDRESS_FOR_TRANSACTION":  7,
	"DECLINE_REQUEST_ADDRESS_FOR_TRANSACTION": 8,
	"REQUEST_TRANSACTION":                     9,
	"SEND_TRANSACTION":                        10,
	"DECLINE_REQUEST_TRANSACTION":             11,
	"SYNC_INSTALLATION_CONTACT":               12,
	"SYNC_INSTALLATION_ACCOUNT":               13,
	"SYNC_INSTALLATION_PUBLIC_CHAT":           14,
	"CONTACT_CODE_ADVERTISEMENT":              15,
	"PUSH_NOTIFICATION_REGISTRATION":          16,
	"PUSH_NOTIFICATION_REGISTRATION_RESPONSE": 17,
	"PUSH_NOTIFICATION_QUERY":                 18,
	"PUSH_NOTIFICATION_QUERY_RESPONSE":        19,
	"PUSH_NOTIFICATION_REQUEST":               20,
	"PUSH_NOTIFICATION_RESPONSE":              21,
	"EMOJI_REACTION":                          22,
	"GROUP_CHAT_INVITATION":                   23,
	"CHAT_IDENTITY":                           24,
	"COMMUNITY_DESCRIPTION":                   25,
	"COMMUNITY_INVITATION":                    26,
	"COMMUNITY_REQUEST_TO_JOIN":               27,
	"PIN_MESSAGE":                             28,
	"EDIT_MESSAGE":                            29,
	"STATUS_UPDATE":                           30,
	"DELETE_MESSAGE":                          31,
	"SYNC_INSTALLATION_COMMUNITY":             32,
	"ANONYMOUS_METRIC_BATCH":                  33,
	"SYNC_CHAT_REMOVED":                       34,
	"SYNC_CHAT_MESSAGES_READ":                 35,
	"BACKUP":                                  36,
	"SYNC_ACTIVITY_CENTER_READ":               37,
	"SYNC_ACTIVITY_CENTER_ACCEPTED":           38,
	"SYNC_ACTIVITY_CENTER_DISMISSED":          39,
	"SYNC_BOOKMARK":                           40,
	"SYNC_CLEAR_HISTORY":                      41,
	"SYNC_SETTING":                            42,
}

func (x ApplicationMetadataMessage_Type) String() string {
	return proto.EnumName(ApplicationMetadataMessage_Type_name, int32(x))
}

func (ApplicationMetadataMessage_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ad09a6406fcf24c7, []int{0, 0}
}

type ApplicationMetadataMessage struct {
	// Signature of the payload field
	Signature []byte `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	// This is the encoded protobuf of the application level message, i.e ChatMessage
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	// The type of protobuf message sent
	Type                 ApplicationMetadataMessage_Type `protobuf:"varint,3,opt,name=type,proto3,enum=protobuf.ApplicationMetadataMessage_Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *ApplicationMetadataMessage) Reset()         { *m = ApplicationMetadataMessage{} }
func (m *ApplicationMetadataMessage) String() string { return proto.CompactTextString(m) }
func (*ApplicationMetadataMessage) ProtoMessage()    {}
func (*ApplicationMetadataMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad09a6406fcf24c7, []int{0}
}
func (m *ApplicationMetadataMessage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ApplicationMetadataMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ApplicationMetadataMessage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ApplicationMetadataMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationMetadataMessage.Merge(m, src)
}
func (m *ApplicationMetadataMessage) XXX_Size() int {
	return m.Size()
}
func (m *ApplicationMetadataMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationMetadataMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationMetadataMessage proto.InternalMessageInfo

func (m *ApplicationMetadataMessage) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *ApplicationMetadataMessage) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *ApplicationMetadataMessage) GetType() ApplicationMetadataMessage_Type {
	if m != nil {
		return m.Type
	}
	return ApplicationMetadataMessage_UNKNOWN
}

func init() {
	proto.RegisterEnum("protobuf.ApplicationMetadataMessage_Type", ApplicationMetadataMessage_Type_name, ApplicationMetadataMessage_Type_value)
	proto.RegisterType((*ApplicationMetadataMessage)(nil), "protobuf.ApplicationMetadataMessage")
}

func init() {
	proto.RegisterFile("application_metadata_message.proto", fileDescriptor_ad09a6406fcf24c7)
}

var fileDescriptor_ad09a6406fcf24c7 = []byte{
	// 741 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0xcd, 0x6e, 0x1b, 0x37,
	0x10, 0x8e, 0x12, 0xd7, 0x8e, 0x47, 0x8e, 0x43, 0x33, 0xfe, 0x91, 0xe5, 0x48, 0x56, 0x94, 0x34,
	0x71, 0x52, 0x40, 0x05, 0xda, 0x63, 0xd1, 0x03, 0x45, 0x4e, 0x24, 0x46, 0x5a, 0x72, 0x43, 0x72,
	0x55, 0xa8, 0x17, 0x62, 0xd3, 0xa8, 0x81, 0x81, 0xc4, 0x12, 0x6c, 0xf9, 0xe0, 0x37, 0xe9, 0x23,
	0xf4, 0x29, 0x7a, 0xee, 0xb1, 0x8f, 0x50, 0xb8, 0x2f, 0x52, 0x70, 0x57, 0x7f, 0xb6, 0xe5, 0xf8,
	0x24, 0xf1, 0xfb, 0x3e, 0xce, 0x70, 0xbe, 0x99, 0x59, 0xa8, 0xa7, 0xa3, 0xd1, 0xe7, 0xe3, 0xdf,
	0xd2, 0xf1, 0xf1, 0xf0, 0xc4, 0x7f, 0x19, 0x8c, 0xd3, 0x8f, 0xe9, 0x38, 0xf5, 0x5f, 0x06, 0x67,
	0x67, 0xe9, 0xa7, 0x41, 0x63, 0x74, 0x3a, 0x1c, 0x0f, 0xe9, 0xc3, 0xec, 0xe7, 0xc3, 0xf9, 0xef,
	0xf5, 0xbf, 0x00, 0xca, 0x6c, 0x7e, 0x21, 0x9a, 0xe8, 0xa3, 0x5c, 0x4e, 0x9f, 0xc2, 0xfa, 0xd9,
	0xf1, 0xa7, 0x93, 0x74, 0x7c, 0x7e, 0x3a, 0x28, 0x15, 0x6a, 0x85, 0xa3, 0x0d, 0x33, 0x07, 0x68,
	0x09, 0xd6, 0x46, 0xe9, 0xc5, 0xe7, 0x61, 0xfa, 0xb1, 0x74, 0x3f, 0xe3, 0xa6, 0x47, 0xfa, 0x33,
	0xac, 0x8c, 0x2f, 0x46, 0x83, 0xd2, 0x83, 0x5a, 0xe1, 0x68, 0xf3, 0x87, 0xd7, 0x8d, 0x69, 0xbe,
	0xc6, 0xed, 0xb9, 0x1a, 0xee, 0x62, 0x34, 0x30, 0xd9, 0xb5, 0xfa, 0x9f, 0xeb, 0xb0, 0x12, 0x8e,
	0xb4, 0x08, 0x6b, 0x89, 0xea, 0x28, 0xfd, 0x8b, 0x22, 0xf7, 0x28, 0x81, 0x0d, 0xde, 0x66, 0xce,
	0x47, 0x68, 0x2d, 0x6b, 0x21, 0x29, 0x50, 0x0a, 0x9b, 0x5c, 0x2b, 0xc7, 0xb8, 0xf3, 0x49, 0x2c,
	0x98, 0x43, 0x72, 0x9f, 0x56, 0x60, 0x3f, 0xc2, 0xa8, 0x89, 0xc6, 0xb6, 0x65, 0x3c, 0x81, 0x67,
	0x57, 0x1e, 0xd0, 0x1d, 0xd8, 0x8a, 0x99, 0x34, 0x5e, 0x2a, 0xeb, 0x58, 0xb7, 0xcb, 0x9c, 0xd4,
	0x8a, 0xac, 0x04, 0xd8, 0xf6, 0x15, 0xbf, 0x0a, 0x7f, 0x43, 0x9f, 0xc3, 0xa1, 0xc1, 0xf7, 0x09,
	0x5a, 0xe7, 0x99, 0x10, 0x06, 0xad, 0xf5, 0x6f, 0xb5, 0xf1, 0xce, 0x30, 0x65, 0x19, 0xcf, 0x44,
	0xab, 0xf4, 0x0d, 0xbc, 0x64, 0x9c, 0x63, 0xec, 0xfc, 0x5d, 0xda, 0x35, 0xfa, 0x1d, 0xbc, 0x12,
	0xc8, 0xbb, 0x52, 0xe1, 0x9d, 0xe2, 0x87, 0x74, 0x0f, 0x9e, 0x4c, 0x45, 0x8b, 0xc4, 0x3a, 0xdd,
	0x06, 0x62, 0x51, 0x89, 0x2b, 0x28, 0xd0, 0x43, 0x38, 0xb8, 0x1e, 0x7b, 0x51, 0x50, 0x0c, 0xd6,
	0xdc, 0x28, 0xd2, 0x4f, 0x0c, 0x24, 0x1b, 0xcb, 0x69, 0xc6, 0xb9, 0x4e, 0x94, 0x23, 0x8f, 0xe8,
	0x33, 0xa8, 0xdc, 0xa4, 0xe3, 0xa4, 0xd9, 0x95, 0xdc, 0x87, 0xbe, 0x90, 0x4d, 0x5a, 0x85, 0xf2,
	0xb4, 0x1f, 0x5c, 0x0b, 0xf4, 0x4c, 0xf4, 0xd0, 0x38, 0x69, 0x31, 0x42, 0xe5, 0xc8, 0x63, 0x5a,
	0x87, 0x6a, 0x9c, 0xd8, 0xb6, 0x57, 0xda, 0xc9, 0xb7, 0x92, 0xe7, 0x21, 0x0c, 0xb6, 0xa4, 0x75,
	0x26, 0xb7, 0x9c, 0x04, 0x87, 0xbe, 0xae, 0xf1, 0x06, 0x6d, 0xac, 0x95, 0x45, 0xb2, 0x45, 0x0f,
	0x60, 0xef, 0xa6, 0xf8, 0x7d, 0x82, 0xa6, 0x4f, 0x28, 0x7d, 0x01, 0xb5, 0x5b, 0xc8, 0x79, 0x88,
	0x27, 0xa1, 0xea, 0x65, 0xf9, 0x32, 0xff, 0xc8, 0x76, 0x28, 0x69, 0x19, 0x3d, 0xb9, 0xbe, 0x13,
	0x46, 0x10, 0x23, 0xfd, 0x4e, 0x7a, 0x83, 0x13, 0x9f, 0x77, 0xe9, 0x3e, 0xec, 0xb4, 0x8c, 0x4e,
	0xe2, 0xcc, 0x16, 0x2f, 0x55, 0x4f, 0xba, 0xbc, 0xba, 0x3d, 0xba, 0x05, 0x8f, 0x72, 0x50, 0xa0,
	0x72, 0xd2, 0xf5, 0x49, 0x29, 0xa8, 0xb9, 0x8e, 0xa2, 0x44, 0x49, 0xd7, 0xf7, 0x02, 0x2d, 0x37,
	0x32, 0xce, 0xd4, 0xfb, 0xb4, 0x04, 0xdb, 0x73, 0x6a, 0x21, 0x4e, 0x39, 0xbc, 0x7a, 0xce, 0xcc,
	0xba, 0xad, 0xfd, 0x3b, 0x2d, 0x15, 0x39, 0xa0, 0x8f, 0xa1, 0x18, 0x4b, 0x35, 0x1b, 0xfb, 0xa7,
	0x61, 0x77, 0x50, 0xc8, 0xf9, 0xee, 0x54, 0xc2, 0x4b, 0xac, 0x63, 0x2e, 0xb1, 0xd3, 0xd5, 0xa9,
	0x86, 0x5a, 0x04, 0x76, 0x71, 0x61, 0x5f, 0x0e, 0xc3, 0x50, 0x2d, 0x9b, 0x99, 0x49, 0x6a, 0x52,
	0xa3, 0x65, 0xd8, 0x65, 0x4a, 0xab, 0x7e, 0xa4, 0x13, 0xeb, 0x23, 0x74, 0x46, 0x72, 0xdf, 0x64,
	0x8e, 0xb7, 0xc9, 0xb3, 0xd9, 0x56, 0x65, 0x25, 0x1b, 0x8c, 0x74, 0x0f, 0x05, 0xa9, 0x87, 0xae,
	0xcd, 0xe1, 0x49, 0x2a, 0x1b, 0x0c, 0x14, 0xe4, 0x39, 0x05, 0x58, 0x6d, 0x32, 0xde, 0x49, 0x62,
	0xf2, 0x62, 0x36, 0x91, 0xc1, 0xd9, 0x5e, 0xa8, 0x94, 0xa3, 0x72, 0x68, 0x72, 0xe9, 0xb7, 0xb3,
	0x89, 0xbc, 0x4e, 0xe7, 0xdb, 0x88, 0x82, 0xbc, 0x0c, 0x13, 0xb7, 0x54, 0x22, 0xa4, 0x8d, 0xa4,
	0xb5, 0x28, 0xc8, 0xab, 0xcc, 0x89, 0xa0, 0x69, 0x6a, 0xdd, 0x89, 0x98, 0xe9, 0x90, 0x23, 0xba,
	0x0b, 0x34, 0x7f, 0x61, 0x17, 0x99, 0xf1, 0x6d, 0x69, 0x9d, 0x36, 0x7d, 0xf2, 0x3a, 0xd8, 0x98,
	0xe1, 0x16, 0x9d, 0x93, 0xaa, 0x45, 0xde, 0x34, 0x2b, 0x7f, 0x5f, 0x56, 0x0b, 0xff, 0x5c, 0x56,
	0x0b, 0xff, 0x5e, 0x56, 0x0b, 0x7f, 0xfc, 0x57, 0xbd, 0xf7, 0x6b, 0xb1, 0xf1, 0xfd, 0x4f, 0xd3,
	0xef, 0xdd, 0x87, 0xd5, 0xec, 0xdf, 0x8f, 0xff, 0x07, 0x00, 0x00, 0xff, 0xff, 0x83, 0xe5, 0x03,
	0xed, 0x96, 0x05, 0x00, 0x00,
}

func (m *ApplicationMetadataMessage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ApplicationMetadataMessage) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ApplicationMetadataMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Type != 0 {
		i = encodeVarintApplicationMetadataMessage(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Payload) > 0 {
		i -= len(m.Payload)
		copy(dAtA[i:], m.Payload)
		i = encodeVarintApplicationMetadataMessage(dAtA, i, uint64(len(m.Payload)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintApplicationMetadataMessage(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintApplicationMetadataMessage(dAtA []byte, offset int, v uint64) int {
	offset -= sovApplicationMetadataMessage(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ApplicationMetadataMessage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovApplicationMetadataMessage(uint64(l))
	}
	l = len(m.Payload)
	if l > 0 {
		n += 1 + l + sovApplicationMetadataMessage(uint64(l))
	}
	if m.Type != 0 {
		n += 1 + sovApplicationMetadataMessage(uint64(m.Type))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovApplicationMetadataMessage(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozApplicationMetadataMessage(x uint64) (n int) {
	return sovApplicationMetadataMessage(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ApplicationMetadataMessage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApplicationMetadataMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ApplicationMetadataMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ApplicationMetadataMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApplicationMetadataMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthApplicationMetadataMessage
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthApplicationMetadataMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = append(m.Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Signature == nil {
				m.Signature = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payload", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApplicationMetadataMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthApplicationMetadataMessage
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthApplicationMetadataMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Payload = append(m.Payload[:0], dAtA[iNdEx:postIndex]...)
			if m.Payload == nil {
				m.Payload = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApplicationMetadataMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= ApplicationMetadataMessage_Type(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipApplicationMetadataMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthApplicationMetadataMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipApplicationMetadataMessage(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowApplicationMetadataMessage
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowApplicationMetadataMessage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowApplicationMetadataMessage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthApplicationMetadataMessage
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupApplicationMetadataMessage
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthApplicationMetadataMessage
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthApplicationMetadataMessage        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowApplicationMetadataMessage          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupApplicationMetadataMessage = fmt.Errorf("proto: unexpected end of group")
)
