// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: emoji_reaction.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EmojiReaction_Type int32

const (
	EmojiReaction_UNKNOWN_EMOJI_REACTION_TYPE EmojiReaction_Type = 0
	EmojiReaction_LOVE                        EmojiReaction_Type = 1
	EmojiReaction_THUMBS_UP                   EmojiReaction_Type = 2
	EmojiReaction_THUMBS_DOWN                 EmojiReaction_Type = 3
	EmojiReaction_LAUGH                       EmojiReaction_Type = 4
	EmojiReaction_SAD                         EmojiReaction_Type = 5
	EmojiReaction_ANGRY                       EmojiReaction_Type = 6
)

var EmojiReaction_Type_name = map[int32]string{
	0: "UNKNOWN_EMOJI_REACTION_TYPE",
	1: "LOVE",
	2: "THUMBS_UP",
	3: "THUMBS_DOWN",
	4: "LAUGH",
	5: "SAD",
	6: "ANGRY",
}

var EmojiReaction_Type_value = map[string]int32{
	"UNKNOWN_EMOJI_REACTION_TYPE": 0,
	"LOVE":                        1,
	"THUMBS_UP":                   2,
	"THUMBS_DOWN":                 3,
	"LAUGH":                       4,
	"SAD":                         5,
	"ANGRY":                       6,
}

func (x EmojiReaction_Type) String() string {
	return proto.EnumName(EmojiReaction_Type_name, int32(x))
}

func (EmojiReaction_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0a088c907bbc7ed6, []int{0, 0}
}

type EmojiReaction struct {
	// clock Lamport timestamp of the chat message
	Clock uint64 `protobuf:"varint,1,opt,name=clock,proto3" json:"clock,omitempty"`
	// chat_id the ID of the chat the message belongs to, for query efficiency the chat_id is stored in the db even though the
	// target message also stores the chat_id
	ChatId string `protobuf:"bytes,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	// message_id the ID of the target message that the user wishes to react to
	MessageId string `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// message_type is (somewhat confusingly) the ID of the type of chat the message belongs to
	MessageType MessageType `protobuf:"varint,4,opt,name=message_type,json=messageType,proto3,enum=protobuf.MessageType" json:"message_type,omitempty"`
	// type the ID of the emoji the user wishes to react with
	Type EmojiReaction_Type `protobuf:"varint,5,opt,name=type,proto3,enum=protobuf.EmojiReaction_Type" json:"type,omitempty"`
	// whether this is a rectraction of a previously sent emoji
	Retracted bool `protobuf:"varint,6,opt,name=retracted,proto3" json:"retracted,omitempty"`
	// Grant for organisation chat messages
	Grant                []byte   `protobuf:"bytes,7,opt,name=grant,proto3" json:"grant,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmojiReaction) Reset()         { *m = EmojiReaction{} }
func (m *EmojiReaction) String() string { return proto.CompactTextString(m) }
func (*EmojiReaction) ProtoMessage()    {}
func (*EmojiReaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a088c907bbc7ed6, []int{0}
}
func (m *EmojiReaction) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EmojiReaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EmojiReaction.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EmojiReaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmojiReaction.Merge(m, src)
}
func (m *EmojiReaction) XXX_Size() int {
	return m.Size()
}
func (m *EmojiReaction) XXX_DiscardUnknown() {
	xxx_messageInfo_EmojiReaction.DiscardUnknown(m)
}

var xxx_messageInfo_EmojiReaction proto.InternalMessageInfo

func (m *EmojiReaction) GetClock() uint64 {
	if m != nil {
		return m.Clock
	}
	return 0
}

func (m *EmojiReaction) GetChatId() string {
	if m != nil {
		return m.ChatId
	}
	return ""
}

func (m *EmojiReaction) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *EmojiReaction) GetMessageType() MessageType {
	if m != nil {
		return m.MessageType
	}
	return MessageType_UNKNOWN_MESSAGE_TYPE
}

func (m *EmojiReaction) GetType() EmojiReaction_Type {
	if m != nil {
		return m.Type
	}
	return EmojiReaction_UNKNOWN_EMOJI_REACTION_TYPE
}

func (m *EmojiReaction) GetRetracted() bool {
	if m != nil {
		return m.Retracted
	}
	return false
}

func (m *EmojiReaction) GetGrant() []byte {
	if m != nil {
		return m.Grant
	}
	return nil
}

func init() {
	proto.RegisterEnum("protobuf.EmojiReaction_Type", EmojiReaction_Type_name, EmojiReaction_Type_value)
	proto.RegisterType((*EmojiReaction)(nil), "protobuf.EmojiReaction")
}

func init() { proto.RegisterFile("emoji_reaction.proto", fileDescriptor_0a088c907bbc7ed6) }

var fileDescriptor_0a088c907bbc7ed6 = []byte{
	// 355 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0xcd, 0x8e, 0x9a, 0x50,
	0x14, 0xc7, 0xbd, 0x0a, 0x28, 0x07, 0x6d, 0xc9, 0x8d, 0x4d, 0x49, 0xab, 0x94, 0xb8, 0x62, 0x45,
	0x9b, 0x76, 0xd3, 0xa4, 0x2b, 0xac, 0x44, 0x69, 0x15, 0xcc, 0x15, 0x6a, 0xec, 0x86, 0x20, 0xdc,
	0x5a, 0xdb, 0x41, 0x08, 0xe2, 0xc2, 0x37, 0x99, 0x47, 0x9a, 0xe5, 0x3c, 0xc2, 0xc4, 0x79, 0x80,
	0x79, 0x85, 0x09, 0x17, 0x8d, 0x99, 0xd5, 0xbd, 0xbf, 0xff, 0x47, 0xce, 0x39, 0xd0, 0xa5, 0x49,
	0xfa, 0x6f, 0x1b, 0xe4, 0x34, 0x8c, 0x8a, 0x6d, 0xba, 0x33, 0xb2, 0x3c, 0x2d, 0x52, 0xdc, 0x62,
	0xcf, 0xfa, 0xf0, 0xe7, 0x9d, 0x44, 0x77, 0x87, 0x64, 0x5f, 0xc9, 0x83, 0xa7, 0x3a, 0x74, 0xac,
	0x32, 0x4f, 0xce, 0x71, 0xdc, 0x05, 0x3e, 0xba, 0x49, 0xa3, 0xff, 0x0a, 0xd2, 0x90, 0xce, 0x91,
	0x0a, 0xf0, 0x5b, 0x68, 0x46, 0x7f, 0xc3, 0x22, 0xd8, 0xc6, 0x4a, 0x5d, 0x43, 0xba, 0x48, 0x84,
	0x12, 0xed, 0x18, 0xf7, 0x01, 0x12, 0xba, 0xdf, 0x87, 0x1b, 0x5a, 0x7a, 0x0d, 0xe6, 0x89, 0x67,
	0xc5, 0x8e, 0xf1, 0x57, 0x68, 0x5f, 0xec, 0xe2, 0x98, 0x51, 0x85, 0xd3, 0x90, 0xfe, 0xea, 0xf3,
	0x1b, 0xe3, 0xb2, 0x8d, 0x31, 0xab, 0x5c, 0xef, 0x98, 0x51, 0x22, 0x25, 0x57, 0xc0, 0x9f, 0x80,
	0x63, 0x0d, 0x9e, 0x35, 0x7a, 0xd7, 0xc6, 0x8b, 0x75, 0x0d, 0x56, 0x64, 0x49, 0xdc, 0x03, 0x31,
	0xa7, 0x45, 0x1e, 0x46, 0x05, 0x8d, 0x15, 0x41, 0x43, 0x7a, 0x8b, 0x5c, 0x85, 0xf2, 0xae, 0x4d,
	0x1e, 0xee, 0x0a, 0xa5, 0xa9, 0x21, 0xbd, 0x4d, 0x2a, 0x18, 0x64, 0xc0, 0xb1, 0x69, 0x1f, 0xe0,
	0xbd, 0xef, 0xfc, 0x74, 0xdc, 0xa5, 0x13, 0x58, 0x33, 0xf7, 0x87, 0x1d, 0x10, 0xcb, 0xfc, 0xee,
	0xd9, 0xae, 0x13, 0x78, 0xab, 0xb9, 0x25, 0xd7, 0x70, 0x0b, 0xb8, 0xa9, 0xfb, 0xcb, 0x92, 0x11,
	0xee, 0x80, 0xe8, 0x4d, 0xfc, 0xd9, 0x70, 0x11, 0xf8, 0x73, 0xb9, 0x8e, 0x5f, 0x83, 0x74, 0xc6,
	0x91, 0xbb, 0x74, 0xe4, 0x06, 0x16, 0x81, 0x9f, 0x9a, 0xfe, 0x78, 0x22, 0x73, 0xb8, 0x09, 0x8d,
	0x85, 0x39, 0x92, 0xf9, 0x52, 0x33, 0x9d, 0x31, 0x59, 0xc9, 0xc2, 0xb0, 0x7f, 0x77, 0x52, 0xd1,
	0xfd, 0x49, 0x45, 0x0f, 0x27, 0x15, 0xdd, 0x3e, 0xaa, 0xb5, 0xdf, 0x92, 0xf1, 0xf1, 0xdb, 0xe5,
	0xba, 0xb5, 0xc0, 0x7e, 0x5f, 0x9e, 0x03, 0x00, 0x00, 0xff, 0xff, 0x13, 0x32, 0xba, 0x78, 0xc6,
	0x01, 0x00, 0x00,
}

func (m *EmojiReaction) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EmojiReaction) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EmojiReaction) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Grant) > 0 {
		i -= len(m.Grant)
		copy(dAtA[i:], m.Grant)
		i = encodeVarintEmojiReaction(dAtA, i, uint64(len(m.Grant)))
		i--
		dAtA[i] = 0x3a
	}
	if m.Retracted {
		i--
		if m.Retracted {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	if m.Type != 0 {
		i = encodeVarintEmojiReaction(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x28
	}
	if m.MessageType != 0 {
		i = encodeVarintEmojiReaction(dAtA, i, uint64(m.MessageType))
		i--
		dAtA[i] = 0x20
	}
	if len(m.MessageId) > 0 {
		i -= len(m.MessageId)
		copy(dAtA[i:], m.MessageId)
		i = encodeVarintEmojiReaction(dAtA, i, uint64(len(m.MessageId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ChatId) > 0 {
		i -= len(m.ChatId)
		copy(dAtA[i:], m.ChatId)
		i = encodeVarintEmojiReaction(dAtA, i, uint64(len(m.ChatId)))
		i--
		dAtA[i] = 0x12
	}
	if m.Clock != 0 {
		i = encodeVarintEmojiReaction(dAtA, i, uint64(m.Clock))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintEmojiReaction(dAtA []byte, offset int, v uint64) int {
	offset -= sovEmojiReaction(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EmojiReaction) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Clock != 0 {
		n += 1 + sovEmojiReaction(uint64(m.Clock))
	}
	l = len(m.ChatId)
	if l > 0 {
		n += 1 + l + sovEmojiReaction(uint64(l))
	}
	l = len(m.MessageId)
	if l > 0 {
		n += 1 + l + sovEmojiReaction(uint64(l))
	}
	if m.MessageType != 0 {
		n += 1 + sovEmojiReaction(uint64(m.MessageType))
	}
	if m.Type != 0 {
		n += 1 + sovEmojiReaction(uint64(m.Type))
	}
	if m.Retracted {
		n += 2
	}
	l = len(m.Grant)
	if l > 0 {
		n += 1 + l + sovEmojiReaction(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovEmojiReaction(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEmojiReaction(x uint64) (n int) {
	return sovEmojiReaction(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EmojiReaction) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEmojiReaction
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EmojiReaction: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EmojiReaction: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Clock", wireType)
			}
			m.Clock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmojiReaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Clock |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChatId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmojiReaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEmojiReaction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEmojiReaction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChatId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessageId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmojiReaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEmojiReaction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEmojiReaction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MessageId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessageType", wireType)
			}
			m.MessageType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmojiReaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MessageType |= MessageType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmojiReaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= EmojiReaction_Type(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Retracted", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmojiReaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Retracted = bool(v != 0)
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Grant", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmojiReaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEmojiReaction
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEmojiReaction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Grant = append(m.Grant[:0], dAtA[iNdEx:postIndex]...)
			if m.Grant == nil {
				m.Grant = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEmojiReaction(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEmojiReaction
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEmojiReaction(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEmojiReaction
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEmojiReaction
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEmojiReaction
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEmojiReaction
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEmojiReaction
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEmojiReaction
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEmojiReaction        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEmojiReaction          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEmojiReaction = fmt.Errorf("proto: unexpected end of group")
)
